### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by kolf** [pinguinjkeke/vue-local-storage#1]
vue-localstorage.es2015.js:103Uncaught SyntaxError: Unexpected token export

**Comment by pinguinjkeke** [comment]
Thank you for response. I found that v.ES2015 is unusable now. You can import it with this code right now:

``` js
import VueLocalStorage from 'vue-localstorage/vue-localstorage'
```

I'll fix it ASAP

**Comment by pinguinjkeke** [comment]
package.json uses common JS version by default now. ES2015 version is created for manual import in your project.
