### ISSUE TITLE
Document error in README

### ISSUE THREAD

**Issue by huguangju** [pinguinjkeke/vue-local-storage#12]
in usage:
```js
// Use localStorage from Vue object
Vue.$localStorage.set('someNumber', 123)
```
but it report `Uncaught TypeError: Cannot read property 'set' of undefined` when i use in my project.

I checked the source code:

```js
Vue.localStorage = VueLocalStorage
Vue.prototype.$localStorage = VueLocalStorage
```

So the correct way to use it is 

```js
Vue.localStorage.set('someNumber', 123)
```

**Comment by pinguinjkeke** [comment]
@huguangju Thank you for the report. It's fixed now
