### ISSUE TITLE
LS as objects from vuex-persistedstate

### ISSUE THREAD

**Issue by AlesRFK** [pinguinjkeke/vue-local-storage#15]
Hello, I am storing my states in localStorage and problem is that this plugin store all objects in one big object and so on. Is there any way how to remove one specific obj. 
I see in the doc. how to remove specific string but this is something that parsing to JSON.slice and back could solve. Or do you have something else on mind?

**Comment by pinguinjkeke** [comment]
Hi, are you talking about reactivity? Storage is not reactive (should it be?)
```
// You should provide it's definition inside Vue instance/component
localStorage: {
  someArray: { type: Array }
}

// Than get it from localStorage, modify and write back
const someArray = this.$localStorage.get('someArray')
this.$localStorage.set('someArray', someArray.slice(1, 3))
```
Did I understand you correctly? (if not, provide some code)

**Comment by AlesRFK** [comment]
It is object of objects so slice is useless. Tryed get->string->JSON->delete->string->set
Nevertheless the main problem is in the webpack. I went almost crazy, because after hour even removing whole storage done nothing :(
So I restarted dev-server and I don't even need that reactivity anymore ...  
Thank you =)
