### ISSUE TITLE
Server Side Rendering is not supported

### ISSUE THREAD

**Issue by wilk** [pinguinjkeke/vue-local-storage#17]
SSR support needed:

> ReferenceError: window is not defined

**Comment by pinguinjkeke** [comment]
Hi! How can I check it? Can you provide SSR project with VueLocalStorage example, so I can test it?
Is it just a new Vue release with SSR support or nuxt?

**Comment by wilk** [comment]
You can take this boilerplate and add vue-localstorage: https://github.com/vuejs/vue-hackernews-2.0
You'll be noticed with the same error above.

**Comment by pinguinjkeke** [comment]
Ok, I'll check it ASAP
