### ISSUE TITLE
Test for localStorage support *may* be insufficient

### ISSUE THREAD

**Issue by grempe** [pinguinjkeke/vue-local-storage#2]
"Browsers that support localStorage will have a property on the window object named localStorage. However, for various reasons, just asserting that property exists may throw exceptions. If it does exist, that is still no guarantee that localStorage is actually available, as various browsers offer settings that disable localStorage. So a browser may support localStorage, but not make it available to the scripts on the page. One example of that is Safari, which in Private Browsing mode gives us an empty localStorage object with a quota of zero, effectively making it unusable. Our feature detect should take these scenarios into account."

See:

https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#Testing_for_support_vs_availability

And:
https://gist.github.com/paulirish/5558557

**Comment by pinguinjkeke** [comment]
Thank you for the test, it's applied into plugin.

**Comment by grempe** [comment]
Cool. Thanks
