### ISSUE TITLE
[0.4.1] Uncaught TypeError: __webpack_require__.i is not a function

### ISSUE THREAD

**Issue by Uriziel01** [pinguinjkeke/vue-local-storage#20]
Hi.
When I update 0.3.0 -> 0.4.1  and running
```
cross-env NODE_ENV=development webpack --watch --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
```
defined inside my admin.js as
```
import VueLocalStorage from 'vue-localstorage';

Vue.use(VueCookie);
Vue.use(Clipboard);
Vue.use(PortalVue);
Vue.use(VueLocalStorage);
```
everything compiled just fine but in the browser Im getting: `Uncaught TypeError: __webpack_require__.i is not a function`. 
![image](https://user-images.githubusercontent.com/568207/29612843-8cf25200-8803-11e7-80cb-4c4f64f47c95.png)

Reverting back to 0.3.0 fixes everything.

My webpack config is rather large, but I can share some parts if you need details. Just let me know that you'll need.

**Comment by pinguinjkeke** [comment]
Hello. Can you write what line reproduces error? Is it available for you?

**Comment by Uriziel01** [comment]
Sure thing, just give me a day or so to get into this as Im quite busy right now 😄

**Comment by pinguinjkeke** [comment]
@Uriziel01 any news?

**Comment by pinguinjkeke** [comment]
@Uriziel01 ping

**Comment by Uriziel01** [comment]
Pong ;)
Sorry mate. I'll check it in few hours.

**Comment by Uriziel01** [comment]
Heh, sorry for the hassle @pinguinjkeke but I've just updated it to #0.4.2 and everything is working like a charm. I don't really know if something changed on my end (I've updated npm, node in the meanwhile) or the new version just fixed my issue.

Sorry for the problem again and have a great day 👍

**Comment by pinguinjkeke** [comment]
@Uriziel01 0.4.2 release was aimed to close issues like yours.
Thank you for the feedback!
