### ISSUE TITLE
How to use it in SSR

### ISSUE THREAD

**Issue by noprom** [pinguinjkeke/vue-local-storage#23]
As mentioned above, when I use it in a SSR project, it throws some error.
Error message:
![image](https://user-images.githubusercontent.com/8455444/30434856-db84d5fc-999a-11e7-9318-9f9feed0a558.png)
So could you please give me some examples about how to use it in SSR?
My code is just like this:
`app.js`
```
import VueLocalStorage from 'vue-localstorage'
Vue.use(VueLocalStorage, {
  name: 'ls'
})
```
And my `login.vue`:
![image](https://user-images.githubusercontent.com/8455444/30434907-01b06af2-999b-11e7-8596-528d68d7637a.png)

Thanks in advance!

**Comment by pinguinjkeke** [comment]
Hi! Thank you for opening an issue.

What packages are you using? Is it nuxt or pure vue with SSR?
It simply checks for ```process.server```, ```process.SERVER_BUILD``` and ```process.env.VUE_ENV``` variables. Can you provide your values of this variables?

**Comment by noprom** [comment]
@pinguinjkeke
These are my variables
In chrom console:
![image](https://user-images.githubusercontent.com/8455444/30511686-fd6d4f1a-9b10-11e7-9159-bb0bdff8c55e.png)
In server console:
![image](https://user-images.githubusercontent.com/8455444/30511694-1b6dbe64-9b11-11e7-990a-6e74612705fd.png)

**Comment by noprom** [comment]
Hi @pinguinjkeke , do you have telegram? So we can communicate interactively.

**Comment by noprom** [comment]
You can chat with me via telegram, http://t.me/tyeenoprom

**Comment by pinguinjkeke** [comment]
@noprom thanks for help with bug hunting

**Comment by SujanKumarK** [comment]
Hi,

@noprom, I am also facing the same problem, can you disclose the solution you gave to @pinguinjkeke  or suggest how to solve it.
