### ISSUE TITLE
Fetching data from the localStorage on hard refresh via (vue-router) does not respect properties of given variables.

### ISSUE THREAD

**Issue by anthdm** [pinguinjkeke/vue-local-storage#25]
For example in vue-router:

```
router.beforeEach((to, from, next) => {
  let user = Vue.localStorage.get('user') 
})
```
If the request comes from in-app routing <strong>user</strong> is indeed an object. But if we hard refresh the page <strong>user</strong> is still a string (JSON.stringified).

<strong>Update</strong>
After digging around I found out that the properties object was empty. So the type of the object <strong>user</strong> is a string, therefore no JSON object parsing has happened. The vue-router triggers the global `beforeEach` method before the `vue-local-storage` component could initialize its properties.

**Comment by pinguinjkeke** [comment]
What if you declare your properties object on the Vue root. Will it change the behavior?

**Comment by anthdm** [comment]
@pinguinjkeke declaring the properties in the Vue root does not change the behavior.

I dug a little deeper and found out that the $options.localStorage object was undefined in the `beforeCreate` method of the `vue-localstorage` mixin while in the `beforeEach` method of the `vue-router`. That's why the properties were empty.

```
Vue.mixin({
      beforeCreate () {
           // this.$options[name] is undefined while in beforeEnter method in vue-router
        if (this.$options[name]) {
```

**Comment by anthdm** [comment]
A fix for this could be to initialize the properties where we register the plugin.

```
Vue.use(VueLocalstorage, {
  user: {
    type: Object,
    default: {}
  }
})
```

**Comment by pinguinjkeke** [comment]
@anthdm the second parameter is for config. May be I should add third parameter to initialise it properly?

**Comment by anthdm** [comment]
@pinguinjkeke  that would be nice.

**Comment by send0xx** [comment]
@anthdm you could access you local storage in hooks.
```
router.beforeEach((to, from, next) => {
    if (to.matched.some(record => record.meta.requiresAuth)) {
        if(router.app.$localStorage.get('token')) {
            // do your stuff there
```
but beware, values in localstorage won't be deserialized (in case of object), don't know if it's bug or no.

**Comment by anthdm** [comment]
@ionmike  well, that's exactly the bug i'm describing.

**Comment by pinguinjkeke** [comment]
Any ideas how to fix it? ```beforeEach``` is happended when component isn't being initialised, so bindings on beforeCreate inside package's mixin aren't setted up.

**Comment by anthdm** [comment]
@pinguinjkeke 'm debugging it now and will try to come up with a fix.

**Comment by anthdm** [comment]
@pinguinjkeke I found the cause of this bug.

The `beforeEach` from vue-router is triggered on its own mixin `beforeCreate`

So basically:
```
Vue.use(router)
Vue.use(localStorage) // if we use localStorage after router its broken

Vue.use(localStorage) // Works perfect
Vue.use(router)
```

The only thing we can do is make sure to use localStorage before vue-router.

**Comment by anthdm** [comment]
After running this in production for a while, using localStorage before vue-router solved this issue.
