### ISSUE TITLE
Call 'npm start build' on WIndows

### ISSUE THREAD

**Issue by nikolay-borzov** [pinguinjkeke/vue-local-storage#28]
Currently doesn't work.
Could we make it [portable](http://opendirective.net/blog/2015/12/writing-portable-npm-build-scripts/)

**Comment by pinguinjkeke** [comment]
Hi, Nikolay.
Thank you for opening the issues. It's awesome.

Can you provide more info? I haven't windows-based PC and can't test it

**Comment by nikolay-borzov** [comment]
Sure. Apparently cmd doesn't recognize `;`
Can you test whether this works on your environment
```json
"build": "npm run build:es && npm run build:main && npm run build:minify",
```
This works on windows - runs one command after another

**Comment by pinguinjkeke** [comment]
Yes it's working
