### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by pinguinjkeke** [pinguinjkeke/vue-local-storage#3]

**Comment by anirudh1800** [comment]
Hi @pinguinjkeke, can I help in writing test cases?

**Comment by pinguinjkeke** [comment]
@anirudhgali It will be really nice! Testing especially in JS is not my strong side.
We need browser tests, which will write and read value from localStorage via plugin and check for correct datatype and correct storage value.

**Comment by pinguinjkeke** [comment]
It will be implemented in 1.0 version
