### ISSUE TITLE
.includes has no support in IE11 and is throwing an error

### ISSUE THREAD

**Issue by Putr** [pinguinjkeke/vue-local-storage#30]
https://github.com/pinguinjkeke/vue-local-storage/blob/c1bd2bdd25712f11e33a4dd58101da72a983abcd/dist/vue-local-storage.js#L56

**Comment by pinguinjkeke** [comment]
Shouldn't you provide .includes polyfill inside your project?

**Comment by prasad83** [comment]
I encountered similar trouble and devise a fix (see [here](https://github.com/pinguinjkeke/vue-local-storage/pull/37))
