### ISSUE TITLE
why number is Int? not Float?

### ISSUE THREAD

**Issue by baryon** [pinguinjkeke/vue-local-storage#33]
why number is Int? not Float?
I suggest add Int type and Float type

**Comment by pinguinjkeke** [comment]
JS has no int and float types. It's all ```Number``` type. Can you provide an example?

**Comment by baryon** [comment]
when we set type to Number, it will be processed as "Int" via parseInt. Isn't it wrong?
if we set `6.02`, get `6`
```
  _process (type, value) {
    switch (type) {
      case Boolean:
        return value === 'true'
      case Number:
        return parseInt(value, 10)
```

**Comment by pinguinjkeke** [comment]
Yes, you're right
