### ISSUE TITLE
Check, if localStorage is available and usable before using it

### ISSUE THREAD

**Issue by fraaalk** [pinguinjkeke/vue-local-storage#35]
The plugin relies on an always accessible and writable localStorage which (at least in our case) leads to alot of errors if its not available. 

It would be easy to prevent those errors if a small check would be implemented first or something similar to the solution described here: https://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st

```javascript
let isSupported;

try {
  localStorage.setItem('vue-localstorage', '');
  localStorage.removeItem('vue-localstorage');

  isSupported = true;
} catch (err) {
  isSupported = false;
}
```

**Comment by pinguinjkeke** [comment]
https://github.com/pinguinjkeke/vue-local-storage/blob/master/src/index.js#L21
This mechanism is implemented. But I think it should return from install method when it catches an exception, right?

**Comment by fraaalk** [comment]
Your right, the check is implemented, but not used. 
Any additional set/get should be dependent on isSupported.

**Comment by fraaalk** [comment]
thanks for fixing it! 
please also provide up-to-date dist files. package.json main is pointing here:

```
"main": "dist/vue-local-storage.js",
```
