### ISSUE TITLE
How to remove all items from localstorage

### ISSUE THREAD

**Issue by FrancescoMussi** [pinguinjkeke/vue-local-storage#40]
I need to empty the localstorage.
Is there a way to remove all the items at once?
Didn't find it in the documentation
Thanks

**Comment by pinguinjkeke** [comment]
Hello. You can simply use localStorage API.
```js
localStorage.clear()
```

You can read more about localStorage interface at mozilla documentation: https://developer.mozilla.org/ru/docs/Web/API/Storage/clear

Please, close the issue if this answer help you.

**Comment by FrancescoMussi** [comment]
Mmh it doesn't seems to work.
I have tried:
`this.$localStorage.clear()`

And it gives the following error:
`this.$localStorage.clear is not a function`

![screen shot 2018-02-08 at 16 25 29](https://user-images.githubusercontent.com/5312907/35977822-be6f4bee-0cec-11e8-9b6d-9cbc4681e6e0.png)

Everything else works fine:
```
this.$localStorage.get
this.$localStorage.set
this.$localStorage.remove
```

**Comment by pinguinjkeke** [comment]
No, you should use global localStorage.
```js
window.localStorage.clear()
```

**Comment by FrancescoMussi** [comment]
Okay thanks in this way it works.
But why I have to use the global localStorage for the clear method?

Would it be possible to include this method and use it as `this.$localStorage.clear()` ?

**Comment by pinguinjkeke** [comment]
@FrancescoMussi I think it shouldn't be part of package because it will repeat already defined standard API.

**Comment by FrancescoMussi** [comment]
Well I think it could probably be more easy to use (and to find in the documentation), but no problem.
Thanks for the help!
