### ISSUE TITLE
Make static method available

### ISSUE THREAD

**Issue by LabiKyo** [pinguinjkeke/vue-local-storage#6]
I'm pretty new to vue so correct me if I was wrong. I think it's better to provide ability to call `get`/`set`/`remove` outside vue instance, like in vuex actions. Vuex and vue-router can do that. I don't know how to access the instance method in vuex action, where I guess all side-effect should be put in. (like redux-saga)

I just make `install` a static method of `VueLocalStorage` class, and export the class, it works. I can make a PR later if this is okay.

**Comment by pinguinjkeke** [comment]
Ok, I'll implement it ASAP

**Comment by gabovanlugo** [comment]
+1

**Comment by Pinary** [comment]
+1

**Comment by leozero** [comment]
+1

**Comment by rtorino** [comment]
@pinguinjkeke Still can't access localStorage object without instantiating Vue.

**Comment by LabiKyo** [comment]
@rtorino you can use `Vue.prototype.localStorage` for now, although i don't think it's the best way.
