### ISSUE TITLE
How can I listen data storage result ?

### ISSUE THREAD

**Issue by laobie** [pinguinjkeke/vue-local-storage#7]
I want to listen data storage result, when it is true to do something, other not.

**Comment by pinguinjkeke** [comment]
Do you mean reactivity in localStorage? Are you want to listen to value change?

**Comment by laobie** [comment]
Yes, I want to listen Whether the data is saved successfully, not the saved data.

**Comment by pinguinjkeke** [comment]
@laobie how can it be not saved? Please, provide a pseudocode example.

I can make a localStorage variables like computed (something like mapGetters from vuex), but it will not see data changed outside current Vue instance

**Comment by laobie** [comment]
When I do like below:

``` javascript
this.$localStorage.set(KEY, token)
this.$router.replace('another_age')
```

And in another page, I get the saved value, but the value is not new.

OK, may I Incorrectly design my code, I'm a beginner.

**Comment by laobie** [comment]
@pinguinjkeke I printed the save data, and found them are same. Sorry I make a mistake.
