### ISSUE TITLE
change state of boleean

### ISSUE THREAD

**Issue by yoavshtainer** [pinguinjkeke/vue-local-storage#8]
Hi! i'm trying to use your repo with .vue files, And the set function not work for me. 

i try this stuff on my Hello.vue file: 
HTML:
`<button v-on:click="change">change</button><br/><br/>`

script: 
 1) `change () {
      let bool = this.$localStorage.get('bolian')
      console.log('$localStorage ', bool)
      if (bool) {
        bool = this.$localStorage.set('bolian', false)
      } else {
        bool = this.$localStorage.set('bolian', true)
      }
      console.log('$localStorage ', bool)`
2) `      let bool = this.$localStorage.get('bolian')
      console.log('$localStorage ', bool)

      bool = this.$localStorage.set('bolian', !this.$localStorage.get('bolian'))

      console.log('$localStorage ', bool)
    }`
3) `    change () {
      let bool = this.$localStorage.get('bolian')
      console.log('$localStorage ', bool)

      bool = this.$localStorage.set('bolian', !bool)

      console.log('$localStorage ', bool)
    }`

I hope you can help me understand my mistake

**Comment by pinguinjkeke** [comment]
What exactly not working? Can you provide jsfiddle?
